### ISSUE TITLE
How to use it in Github Workflow?

### ISSUE THREAD

**Issue by ZedZipDev** [go-to-k/delstack#214]
Can I use this tool in my Github Workflow YML file? How to?

**Comment by go-to-k** [comment]
Hi, @ZedZipDev 

Today, I created GitHub Custom Action.

https://github.com/go-to-k/delstack#github-actions

You can use delstack in Github Workflow YML file, as the following.

```yaml
jobs:
  delstack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Use delstack
        uses: go-to-k/delstack@v1
      - name: Run delstack
        run: |
          delstack -s YourStack
```
